pipeline {
    agent any
    environment {
        GITHUB_TOKEN = credentials('git-cred')
    }
    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/Greeshma-Babu-tech/Jenkins.git', branch: 'main', credentialsId: 'git-cred'
            }
        }
        // Other stages...
    }
}
