pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',changelog: 'false',credentialsId: 'git-creden',git url: 'https://github.com/Greeshma-Babu-tech/Jenkins.git'
            }
        }
        // Other stages...
        stage('Terraform Init') {
             steps {
                 sh 'terraform init'
              }
            }
         stage('Terraform Plan') {
             steps { 
                sh 'terraform plan'
                }
            }
        stage('Terraform Apply') {
             steps {
                 sh 'terraform apply -auto-approve'
              }
            }
    }
}
